"""add user_repositories

Revision ID: 2d7049b489d0
Revises: d099703071ea
Create Date: 2026-08-24 18:53:32.762858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7049b489d0'
down_revision: Union[str, Sequence[str], None] = 'd099703071ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_repositories',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('tracked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_user_repositories_repository_id_repositories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_repositories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'repository_id', name=op.f('pk_user_repositories'))
    )
    op.create_index(op.f('ix_user_repositories_repository_id'), 'user_repositories', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_repositories_repository_id'), table_name='user_repositories')
    op.drop_table('user_repositories')
    # ### end Alembic commands ###
